// Genere CLQ App Factory v2026.07.26-culture-city-bound
const locations=[
    { name: "Château de Rosenborg et Jardin du Roi", lat: 55.68508, lng: 12.57872, audio: "audio/Chateau_de_Rosenborg_et_Jardin_du_Roi.mp3", image: "images/points interets/chateau-de-rosenborg-et-jardin-du-roi.jpg", fallbackImage: "images/points interets/Chateau_de_Rosenborg_et_Jardin_du_Roi.svg" },
    { name: "Tour Ronde — Rundetårn", lat: 55.68132, lng: 12.57578, audio: "audio/Tour_Ronde_Rundetarn.mp3", image: "images/points interets/tour-ronde-rundetarn.jpg", fallbackImage: "images/points interets/Tour_Ronde_Rundetarn.svg" },
    { name: "Cathédrale Notre-Dame — Vor Frue Kirke", lat: 55.67942, lng: 12.57206, audio: "audio/Cathedrale_Notre_Dame_Vor_Frue_Kirke.mp3", image: "images/points interets/cathedrale-notre-dame-vor-frue-kirke.jpg", fallbackImage: "images/points interets/Cathedrale_Notre_Dame_Vor_Frue_Kirke.svg" },
    { name: "Hôtel de Ville et Rådhuspladsen", lat: 55.6759, lng: 12.56899, audio: "audio/Hotel_de_Ville_et_Radhuspladsen.mp3", image: "images/points interets/hotel-de-ville-et-radhuspladsen.jpg", fallbackImage: "images/points interets/Hotel_de_Ville_et_Radhuspladsen.svg" },
    { name: "Jardins de Tivoli", lat: 55.67361, lng: 12.56833, audio: "audio/Jardins_de_Tivoli.mp3", image: "images/points interets/jardins-de-tivoli.jpg", fallbackImage: "images/points interets/Jardins_de_Tivoli.svg" },
    { name: "Ny Carlsberg Glyptotek", lat: 55.67251, lng: 12.57138, audio: "audio/Ny_Carlsberg_Glyptotek.mp3", image: "images/points interets/ny-carlsberg-glyptotek.jpg", fallbackImage: "images/points interets/Ny_Carlsberg_Glyptotek.svg" },
    { name: "Palais de Christiansborg", lat: 55.67626, lng: 12.58023, audio: "audio/Palais_de_Christiansborg.mp3", image: "images/points interets/palais-de-christiansborg.jpg", fallbackImage: "images/points interets/Palais_de_Christiansborg.svg" },
    { name: "Højbro Plads, statue d’Absalon et Gammel Strand", lat: 55.67817, lng: 12.57977, audio: "audio/H_jbro_Plads_statue_d_Absalon_et_Gammel_Strand.mp3", image: "images/points interets/hjbro-plads-statue-dabsalon-et-gammel-strand.jpg", fallbackImage: "images/points interets/H_jbro_Plads_statue_d_Absalon_et_Gammel_Strand.svg" },
    { name: "Kongens Nytorv", lat: 55.68055, lng: 12.5853, audio: "audio/Kongens_Nytorv.mp3", image: "images/points interets/kongens-nytorv.jpg", fallbackImage: "images/points interets/Kongens_Nytorv.svg" },
    { name: "Nyhavn", lat: 55.6797, lng: 12.591, audio: "audio/Nyhavn.mp3", image: "images/points interets/nyhavn.jpg", fallbackImage: "images/points interets/Nyhavn.svg" },
    { name: "Palais d’Amalienborg", lat: 55.68409, lng: 12.59304, audio: "audio/Palais_d_Amalienborg.mp3", image: "images/points interets/palais-damalienborg.jpg", fallbackImage: "images/points interets/Palais_d_Amalienborg.svg" },
    { name: "Église de Marbre — Marmorkirken", lat: 55.68486, lng: 12.58924, audio: "audio/Eglise_de_Marbre_Marmorkirken.mp3", image: "images/points interets/eglise-de-marbre-marmorkirken.jpg", fallbackImage: "images/points interets/Eglise_de_Marbre_Marmorkirken.svg" },
    { name: "Børsen et sa flèche aux dragons", lat: 55.67504, lng: 12.58365, audio: "audio/B_rsen_et_sa_fleche_aux_dragons.mp3", image: "images/points interets/brsen-et-sa-fleche-aux-dragons.jpg", fallbackImage: "images/points interets/B_rsen_et_sa_fleche_aux_dragons.svg" },
    { name: "Diamant Noir — Bibliothèque royale", lat: 55.67395, lng: 12.58571, audio: "audio/Diamant_Noir_Bibliotheque_royale.mp3", image: "images/points interets/diamant-noir-bibliotheque-royale.jpg", fallbackImage: "images/points interets/Diamant_Noir_Bibliotheque_royale.svg" },
    { name: "La Petite Sirène", lat: 55.69286, lng: 12.59928, audio: "audio/La_Petite_Sirene.mp3", image: "images/points interets/la-petite-sirene.jpg", fallbackImage: "images/points interets/La_Petite_Sirene.svg" },
    { name: "Kastellet", lat: 55.69131, lng: 12.59372, audio: "audio/Kastellet.mp3", image: "images/points interets/kastellet.jpg", fallbackImage: "images/points interets/Kastellet.svg" },
    { name: "Fontaine de Gefion et église Saint-Alban", lat: 55.68934, lng: 12.59786, audio: "audio/Fontaine_de_Gefion_et_eglise_Saint_Alban.mp3", image: "images/points interets/fontaine-de-gefion-et-eglise-saint-alban.jpg", fallbackImage: "images/points interets/Fontaine_de_Gefion_et_eglise_Saint_Alban.svg" },
    { name: "Opéra de Copenhague", lat: 55.68216, lng: 12.60093, audio: "audio/Opera_de_Copenhague.mp3", image: "images/points interets/opera-de-copenhague.jpg", fallbackImage: "images/points interets/Opera_de_Copenhague.svg" },
    { name: "Église de Notre-Sauveur — Vor Frelsers Kirke", lat: 55.67248, lng: 12.59409, audio: "audio/Eglise_de_Notre_Sauveur_Vor_Frelsers_Kirke.mp3", image: "images/points interets/eglise-de-notre-sauveur-vor-frelsers-kirke.jpg", fallbackImage: "images/points interets/Eglise_de_Notre_Sauveur_Vor_Frelsers_Kirke.svg" },
    { name: "Freetown Christiania", lat: 55.67426, lng: 12.59749, audio: "audio/Freetown_Christiania.mp3", image: "images/points interets/freetown-christiania.jpg", fallbackImage: "images/points interets/Freetown_Christiania.svg" }
];
const availableCircuits=["petit","moyen","grand"];
const circuits={"petit":[1,2,3,4,5,6,7,8,1],"petit_gare":[1,2,3,4,5,6,7,8,1],"moyen":[9,10,11,12,1,2,3,4,5,6,7,8,13,14,9],"moyen_gare":[9,10,11,12,1,2,3,4,5,6,7,8,13,14,9],"grand":[15,16,17,18,9,10,11,12,1,2,3,4,5,6,7,8,13,14,19,20,15],"grand_gare":[15,16,17,18,9,10,11,12,1,2,3,4,5,6,7,8,13,14,19,20,15]};
const circuitEstimates={"petit":{"distanceKm":4.4,"walkingTimeMinutes":58,"listeningTimeMinutes":56,"totalTimeMinutes":114},"moyen":{"distanceKm":7.4,"walkingTimeMinutes":99,"listeningTimeMinutes":98,"totalTimeMinutes":197},"grand":{"distanceKm":13.6,"walkingTimeMinutes":181,"listeningTimeMinutes":140,"totalTimeMinutes":321}};
